import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";
import PageTitle from "@/components/common/PageTitle";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { customerData } from "@/data";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Image from "next/image";

export default function CustomerDetail() {
  const router = useRouter();
  const [currentCustomer, setCurrentCustomer] = useState(null);
  useEffect(() => {
    if (router.query.id) {
      setCurrentCustomer(
        customerData.find((item) => item.id === router.query.id)
      );
    }
  }, [router]);
  console.log("customer", currentCustomer);
  return (
    <>
      <Head>
        <title>Cutomers List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <PageTitle
          title={"Customer Detail"}
          subtitle={"Here your Customer Detail Profile"}
        />
        <Grid container spacing={2}>
          <Grid size={{ lg: 12, xl: 8 }}>
            <div
              style={{
                backgroundColor: "rgb(240, 243, 246)",
                padding: "30px",
                display: "flex",
                borderRadius: "16px",
                minWidth: "972px",
              }}
            >
              <div>
                <Image src="/avatar.png" alt="" width={222} height={217} />
              </div>
              <div
                style={{
                  maxWidth: "653px",
                  width: "100%",
                  marginLeft: "30px",
                }}
              >
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                  }}
                >
                  <div
                    style={{
                      width: "47.37%",
                      height: "126px",
                      display: "flex",
                      flexDirection: "column",
                      justifyContent: "space-around",
                    }}
                  >
                    <h2>{currentCustomer?.userName}</h2>
                    <p
                      style={{
                        color: "green",
                      }}
                    >
                      UX Designer
                    </p>
                    <p
                      style={{
                        color: "gray",
                      }}
                    >
                      {currentCustomer?.location}
                    </p>
                  </div>
                  <div>
                    <button
                      style={{
                        border: "none",
                        backgroundColor: "unset",
                        marginRight: "20px",
                        width: "60px",
                        height: "60px",
                      }}
                    >
                      <Image src="/info.png" alt="" width={60} height={60} />
                    </button>
                    <button
                      style={{
                        border: "none",
                        backgroundColor: "unset",
                        width: "60px",
                        height: "60px",
                      }}
                    >
                      <Image src="/edit.png" alt="" width={60} height={60} />
                    </button>
                  </div>
                </div>
                <div
                  style={{
                    minWidth: "653px",
                    display: "flex",
                    justifyContent: "space-between",
                    marginTop: "39px",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <Image src="/mail.png" alt="" width={16} height={16}/>
                    <p>eren.yeager@mail.co.id</p>
                  </div>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <Image src="/mail.png" alt="" width={16} height={16}/>
                    <p>+012 345 6789</p>
                  </div>
                  <div
                    style={{
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <Image src="/mail.png" alt="" width={16} height={16}/>
                    <p>Highspeed Studios</p>
                  </div>
                </div>
              </div>
            </div>
          </Grid>
          <Grid
            sx={{
              backgroundColor: "#00B074",
              borderRadius: "16px",
              color: "white",
              minWidth: "457px",
            }}
            size={4}
          >
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "space-around",
                padding: "25px",
              }}
            >
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginBottom: "6px",
                }}
              >
                <p>Your Balance</p>
                <h2>***</h2>
              </div>
              <h1
                style={{
                  fontWeight: "700",
                  fontSize: "52px",
                  lineHeight: "100%",
                  marginBottom: "11px",
                }}
              >
                $9,452
              </h1>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  marginBottom: "6px",
                }}
              >
                <h3>2451 **** **** ****</h3>
                <h3>02/21</h3>
              </div>
            </div>
            <div
              style={{
                backgroundColor: "#33bd8f",
                display: "flex",
                justifyContent: "space-between",
                padding: "25px",
                borderRadius: "16px",
              }}
            >
              <div>
                <p>Name</p>
                <h2>Eren Yeager</h2>
              </div>
              <Image
                src="/master.png"
                alt=""
                width={60}
                height={56}
              />
            </div>
          </Grid>
        </Grid>

        <div
          style={{
            maxWidth: "713px",
            width: "100%",
            backgroundColor: "rgb(240, 243, 246)",
            marginTop: "40px",
            borderRadius: "16px",
          }}
        >
          <div
            style={{
              width: "100%",
              height: "115px",
              padding: "35px",
              display: "flex",
              justifyContent: "space-between",
            }}
          >
            <div>
              <h3
                style={{
                  fontWeight: "500",
                  fontSize: "21px",
                  lineHeight: "100%",
                }}
              >
                Most Ordered Food
              </h3>
              <p
                style={{
                  fontWeight: "400",
                  fontSize: "12px",
                  lineHeight: "18px",
                  color: "#A3A3A3",
                }}
              >
                Lorem ipsum dolor sit amet, consectetur
              </p>
            </div>
            <div
              style={{
                width: "280px",
                height: "48px",
                borderRadius: "24px",
                backgroundColor: "#F3F2F7",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
              }}
            >
              <button
                style={{
                  width: "89.6px",
                  height: "37px",
                  borderRadius: "24px",
                  border: "none",
                  backgroundColor: "white",
                  color: "#5E6C93",
                }}
              >
                Weekly
              </button>
              <button
                style={{
                  width: "89.6px",
                  height: "37px",
                  borderRadius: "24px",
                  border: "none",
                  backgroundColor: "unset",
                  color: "#5E6C93",
                }}
              >
                Daily
              </button>
              <button
                style={{
                  width: "89.6px",
                  height: "37px",
                  borderRadius: "24px",
                  border: "none",
                  backgroundColor: "unset",
                  color: "#5E6C93",
                }}
              >
                Monthly
              </button>
            </div>
          </div>
          <div>
            {currentCustomer?.item?.map((item, index) => (
              <Lists key={index} item={item} />
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

CustomerDetail.getLayout = (pageProps) => (
  <MainLayout>
    <CustomerDetail {...pageProps} />
  </MainLayout>
);

function Lists(props) {
  const { item } = props;
  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <div>
        <Image
          style={{
            marginRight: "30px",
          }}
          src={item.img}
          alt=""
          width={87}
          height={87}
        />
      </div>

      <div
        style={{
          flexGrow: "1",
        }}
      >
        <div>
          <h5>{item.food}</h5>
          <p
            style={{
              color: "#2D9CDB",
            }}
          >
            {" "}
            {item.name}
          </p>
        </div>
        <p>Serves for 4 Person 24mins</p>
      </div>

      <div
        style={{
          display: "flex",
        }}
      >
        <p>${item.cost}</p>
        <button
          style={{
            border: "none",
            backgroundColor: "unset",
            fontWeight: "1000",
            fontSize: "14px",
            marginLeft: "35px",
            marginRight: "20px",
          }}
        >
          ***
        </button>
      </div>
    </Box>
  );
}
