import MainLayout from "@/components/common/layouts/MainLayout";
import Foods from "@/components/pages/foods/Foods";
import Head from "next/head";


export default function Food() {
  
  
  return (
    <>
      <Head>
        <title>Foods</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      
        <Foods />
      </div>
    </>
  );
}

Food.getLayout = (pageProps) => (
  <MainLayout>
    <Food {...pageProps} />
  </MainLayout>
);
