import { orderListData } from "@/data";
import MainLayout from "@/components/common/layouts/MainLayout";
import Allstatus from "@/components/common/Allstatus";
import Button from "@/components/common/Button";
import Table2 from "@/components/common/Table2";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";

function OrderDetail() {
  const router = useRouter();
  const [currentOrder, setCurrentOrder] = useState(null);
  const [tableItems, setTableItems] = useState([]);

  useEffect(() => {
    if (router.query.id) {
      const orderItem = orderListData.find((o) => o.id === router.query.id);
      if (orderItem) {
        setCurrentOrder(orderItem);
        setTableItems(orderItem.items);
      }
    }
  }, [router.query.id]);

  console.log("OrderDetail", currentOrder);

  return (
    <>
      <Head>
        <title>
          {currentOrder ? "Order Detail: " + currentOrder.id : "Order not found"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  
      <div style={{ maxWidth: "1440px" }}>
        <Allstatus id={`Order ID: ${currentOrder?.id}`} />
        <div
          style={{
            display: "flex",
            justifyContent: "space-around",
            padding: "20px",
          }}
        >
          <div
            style={{
              maxWidth: "339px",
              marginRight: "40px",
            }}
          >
            <div
              style={{
                maxHeight: "614px",
                height: "100%",
                width: "100%",
                backgroundColor: "aliceblue",
                display: "flex",
                flexDirection: "column",
                borderRadius: "16px",
              }}
            >
              {/* User Info */}
              {currentOrder ? (
                <div
                  style={{
                    width: "100%",
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "center",
                    justifyContent: "center",
                    textAlign: "center",
                    marginBottom: "20px",
                    height: "317px",
                  }}
                >
                  <img
                    style={{ width: "160px", height: "160px" }}
                    src={currentOrder?.userImage || "/placeholder.png"}
                    alt="User"
                  />
                  <h1
                    style={{
                      marginTop: "27px",
                      fontSize: "18px",
                      fontWeight: "600",
                      marginBottom: "10px",
                    }}
                  >
                    {currentOrder?.userName}
                  </h1>
                  <Button Customers={"Customers"} />
                </div>
              ) : (
                <div>Loading...</div>
              )}
  
              {/* Note Order */}
              <div
                style={{
                  width: "100%",
                  backgroundColor: "#5e6c93",
                  borderRadius: "16px",
                }}
              >
                <div
                  style={{
                    height: "220px",
                    padding: "30px",
                    color: "white",
                  }}
                >
                  <h1
                    style={{
                      fontWeight: "700",
                      fontSize: "24px",
                      marginBottom: "12px",
                    }}
                  >
                    Note Order
                  </h1>
                  <p
                    style={{
                      fontWeight: "400",
                      fontSize: "14px",
                      lineHeight: "24px",
                    }}
                  >
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                    do eiusmod tempor magna aliqua.
                  </p>
                </div>
  
                {/* Location Info */}
                <div
                  style={{
                    backgroundColor: "skyblue",
                    borderRadius: "16px",
                    display: "flex",
                    justifyContent: "space-around",
                    alignItems: "center",
                    padding: "15px",
                    height: "110px",
                  }}
                >
                  <div
                    style={{
                      borderRadius: "50%",
                      width: "49px",
                      height: "49px",
                      backgroundColor: "white",
                      display: "flex",
                      alignItems: "center",
                      justifyContent: "center",
                    }}
                  >
                    <img
                      style={{
                        width: "28px",
                        height: "28px",
                      }}
                      src="/delivir.png"
                      alt="Delivery"
                    />
                  </div>
                  <p
                    style={{
                      width: "157px",
                      fontWeight: "600",
                      lineHeight: "26px",
                      color: "aliceblue",
                      marginLeft: "10px",
                    }}
                  >
                    {currentOrder?.location}
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div>
            <Table2 items={tableItems} />
            <div
              style={{
                height: "599px",
                maxWidth: "1090px",
                width: "100%",
                padding: "30px",
                borderRadius: "12px",
                border: "1px aliceblue",
              }}
            >
              <div
                style={{
                  backgroundImage: "url(/mask.png)",
                  width: "1030px",
                  height: "349px",
                }}
              ></div>
              <div
                style={{
                  marginTop: "43px",
                }}
              >
                <h3>Delivery By</h3>
                <div
                  style={{
                    display: "flex",
                    justifyContent: "space-between",
                    marginTop: "35px",
                  }}
                >
                  {/* Delivery Info */}
                  {currentOrder?.deliveryBy ? (
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                      }}
                    >
                      <img
                        width={87}
                        height={87}
                        src={
                          currentOrder?.deliveryBy.img || "defaultImagePath.jpg"
                        }
                        alt="Delivery by"
                      />
                      <div
                        style={{
                          display: "flex",
                          flexDirection: "column",
                          marginLeft: "30px",
                        }}
                      >
                        <h3>{currentOrder?.deliveryBy.name}</h3>
                        <p>ID- {currentOrder?.deliveryBy.id}</p>
                      </div>
                    </div>
                  ) : (
                    <div>Loading...</div>
                  )}
  
                  {/* Buttons */}
                  <div>
                    <button
                      style={{
                        width: "271px",
                        height: "81px",
                        borderRadius: "12px",
                        border: "1px solid #2D9CDB",
                        backgroundColor: "white",
                        padding: "16px",
                      }}
                    >
                      telphone
                    </button>
                    <button
                      style={{
                        width: "271px",
                        height: "81px",
                        borderRadius: "12px",
                        border: "1px solid #2D9CDB",
                        backgroundColor: "white",
                        padding: "16px",
                      }}
                    >
                      click
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
  
}

OrderDetail.getLayout = (pageProps) => (
  <MainLayout>
    <OrderDetail {...pageProps} />
  </MainLayout>
);

export default OrderDetail;
