import { Box } from "@mui/material";
import Head from "next/head";
import { useUsersWithRestaurants } from "@/hooks/useUsersWithRestaurants";
import { useRouter } from "next/router";
import { GoStarFill } from "react-icons/go";
import useCategory from "@/hooks/useCategories";

export default function Clint() {
  const { users, loading } = useUsersWithRestaurants();

  return (
    <>
      <Head>
        <title>Clint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          maxWidth: "1440px",
          width: "100%",
          margin: "0 auto",
          display: "flex",
          gap: "16px",
          flexWrap: "wrap",
        }}
      >
        {users.map((item) => (
          <ResCard key={item.id} item={item} />
        ))}
      </Box>
    </>
  );
}
function ResCard({ item }) {
  const router = useRouter();
  const handleClick = () => {
    router.push(`/client/res/${item.documentId}`);
    useCategory(item.documentId);
  };
  return (
    <Box
      sx={{
        maxWidth: "340px",
        width: "100%",
        cursor: "pointer",
        opacity: "100%",
        "&:hover": {
          opacity: "80%",
          transition: ".3s",
        },
      }}
      onClick={() => handleClick()}
    >
      <Box sx={{ width: "100%", height: "150px" }}>
        <img
          src="/evos.png"
          alt={item.name || "User"}
          style={{
            width: "100%",
            height: "100%",
            objectFit: "cover",
            borderRadius: "16px",
          }}
        />
      </Box>
      <Box sx={{ padding: "16px" }}>
        <Box
          sx={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
          }}
        >
          <h3 style={{ margin: 0 }}>{item.name || "Topilmadi"}</h3>
          <p style={{ margin: 0, display: "flex", alignItems: "center" }}>
            <GoStarFill /> 5
          </p>
        </Box>
      </Box>
    </Box>
  );
}
