import Head from "next/head";
import MainLayout from "@/components/common/layouts/MainLayout";


export default function Customers() {
  return (
    <>
      <Head>
        <title>New Orders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Husniddin dabba</p>
      </div>
    </>
  );
}

Customers.getLayout = (pageProps) => (
  <MainLayout>
    <Customers {...pageProps} />
  </MainLayout>
);
